---
layout: post
title:  " Building community in a virtual space "
author: Jenny Keshwani
date: 2018-03-09
---
### "Building community in a virtual space”

![Jenny Keshwani]({{ "../assets/jenny.png" | absolute_url }})`
Hello! I’m Jenny Keshwani, faculty member in biological systems engineering. My role as Nebraska Extension science literacy specialist allows me ample opportunities to play with creative and unique educational technologies. So it was no surprise when my friend and colleague, Brad, asked me to join him in developing a makerspace community using virtual reality and telepresence robots.
I was – and maybe still am – a bit skeptical about using technology to build community. I’ve read about the negative effects of technology on relationships – see Alone Together by Sherry Turkle and Generation Me by Jean Twenge – and was nervous about replacing real face-to-face interactions with self-centered/when-I-want-it/on-my-own-time technology-assisted interactions.
However, my first few experiences with virtual collaboration are starting to question my preconceived notions and change my mind.
Our core team generally meets on Zoom, a standard web conference application. Using video chat allows us to see each other’s facial expressions and some body language, a definite improvement over a conference call without video. However, it’s definitely not the same as being physically together in a meeting space. It’s easy to mentally check out on a web conference. Staring at small boxes of your colleague’s faces is not natural or engaging… 
We decided to experiment with Facebook Spaces for our regular meeting to put our talk into practice. If we expect the youth to collaborate and build community virtually, so should we. The Nebraska contingent of the core team – Brad, Dagen, Neal and myself – set-up our Oculus Rifts together at Nebraska Innovation Studio. We were a bit nervous about the technology and wanted to be able to help each other in case we ran into issues with the application. Andy joined us virtually from New York. 
From the moment we all appeared in Facebook Spaces I could tell this was not going to be the typical web conference interaction. Cartoonish avatars of my colleagues were positioned around a table. I could wave to them from across the table and talk to them as if we were in the same room. We proceeded to explore the space together – finding tools like a selfie-stick especially useful to document our time and creative additions, like a bunny ear headband, to our avatars. At one point, Brad pushed a sword through my head. Don’t worry! It didn’t hurt! We also learned how to share pictures with each other and find images to redecorate our room. For a while we even held our meeting on the moon!
Initially I felt that we didn’t accomplish anything related to the project during our one-hour meeting that day. We didn’t follow an agenda or make any plans for moving the project forward. However, there was value in experiencing how to learn to use the virtual space together. We even explored how to take notes to capture our discussion should we decide to be productive during out next meeting in Facebook Places. 
When I took off my Oculus headset I was honestly surprised to find only Dagen, Brad and Neal in the real-world room with me. Andy’s presence in the virtual space was so convincing I actually believed he was in Nebraska attending the meeting in the same room with us. I have *never* felt that way after a Zoom meeting. Maybe there is potential for building meaningful community through virtual technologies after all!
Moving forward I’m excited to continue to explore how technology like Facebook Spaces can be used to build community from a distance. How can we move from a playful, exploration-focused experience to a productive meeting? How will this technology deepen relationships between team members to allow for more creativity? 
